# prometheus/prometheus.yml

scrape_configs:
  - job_name: 'server-metrics'
    scrape_interval: 30s
    metrics_path: '/metrics'
    scheme: 'http'

    static_configs:
      - targets: ['host.docker.internal:4000', 'host.docker.internal:5000']
    basic_auth:
      username: 'admin'
      password: '1234'