export * from './bachelor-thesis-assessments-query.response';
export * from './bachelor-thesis-evaluations-query.response';
export * from './bachelor-thesis-registrations-query.response';
export * from './fields-query.response';
export * from './locations-query.response';
export * from './oral-defense-assessments-query.response';
export * from './oral-defense-registrations-query.response';
export * from './roles-query.response';
export * from './theses-query.response';
export * from './topics-query.response';
export * from './programs-query.response';
export * from './lecturers-query.response';
export * from './notifications-query.response';
export * from './students-query.response';
export * from './users-query.response';

export * from './processes-query.response';
export * from './requests-query.response';
export * from './groups-query.response';