export * from './user.repo';
export * from './refresh-token.repo';
export * from './lecturer.repo';
export * from './bachelor-thesis-registration.repo';
export * from './bachelor-thesis-assessment.repo';
export * from './bachelor-thesis-evaluation.repo';
export * from './oral-defense-registration.repo';
export * from './oral-defense-assessment.repo';
export * from './field.repo';