export const NOT_FOUND_ERROR_MESSAGES = {
    UserNotFound: 'User not found',
    RoleNotFound: 'Role not found',
    AdminNotFound: 'Admin not found',
    StudentNotFound: 'Student not found',
    LecturerNotFound: 'Lecturer not found',
    ThesisNotFound: 'Thesis not found',
    FieldNotFound: 'Field not found',
    TopicNotFound: 'Topic not found',
    LocationNotFound: 'Location not found',
    BachelorThesisRegistrationNotFound: 'Bachelor thesis registration not found',
    OralDefenseRegistrationNotFound: 'Oral defense registration not found',
    BachelorThesisAssessmentNotFound: 'Bachelor thesis assessment not found',
    OralDefenseAssessmentNotFound: 'Oral defense assessment not found',
} as const;