export * from './refresh-token.repo.interface';
export * from './user.repo.interface';
export * from './lecturer.repo.interface';
export * from './bachelor-thesis-registration.repo.interface';
export * from './bachelor-thesis-assessment.repo.interface';
export * from './bachelor-thesis-evaluation.repo.interface';
export * from './oral-defense-registration.repo.interface';
export * from './oral-defense-assessment.repo.interface';
export * from './field.repo.interface';