export const BOOTSTRAP_SETTINGS_KEY = {
    Logger: 'logger',
    Tracer: 'tracer',
    TracerSpecs: 'tracer-specs',
    Container: 'container',
    IocAdapter: 'ioc-adapter',
    ExpressServer: 'express_server',
    ExpressApp: 'express_app',
    ServerUrl: 'server_url',
    RoutingControllersOptions: 'routing_controllers_options',
    IO: 'io',
    SocketControllers: 'socket-controllers',
    SocketAdminUI: 'socket-admin-ui',
    Metrics: 'metrics',
    ServerName: 'server-name',
    Swagger: 'swagger',
} as const;